- name: Deploy Toxicity App
  hosts: localhost
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    image_name: "{{ lookup('env', 'DOCKER_USERNAME') }}/toxicity-app:1.0"

  tasks:

    - name: Check if Docker exists
      command: docker --version
      register: docker_check
      ignore_errors: yes

    - name: Install Docker (skip if already installed)
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: docker_check.failed
      ignore_errors: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
      ignore_errors: yes

    - name: Run Container
      docker_container:
        name: toxicity-app
        image: "{{ image_name }}"
        state: started
        ports:
          - "5000:5000"