name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint
        run: python -m flake8 .

      - name: Test
        run: python -m pytest

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/toxicity-app:1.0 .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/toxicity-app:1.0

      - name: Install Python dependencies for Ansible
        run: pip install requests docker

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook deploy.yml